export const addAdCss = {
    addNewAd: '.elementor-section--handles-inside > div.elementor-element.elementor-element-ab9fff0',
    asset_type: '[data-name="asset_type"]',
    asset_status: '[data-name="asset_status"]',
    city: '[data-name="city"]',
    street: '[data-name="street_1"]',
    street_number: '[data-name="street_number"]',
    nextButton: '.active div.step-nav.ff_step_nav_last button.ff-float-right.ff-btn',
    floor: '[data-name="floor"]',
    floors_amount: '[data-name="floors"]',
    room_num: '[data-name="room_num"]',
    terrace: '[data-name="terrace"]',
    parking: '[data-name="_parking"]',
    built_mr: '[data-name="built_mr"]',
    elevator: '[data-name="elevator_1"]',
    description: '[data-name="asset_description"]',
    credits: '[data-name="credits"]',
    house_committee: '[data-name="house_committee"]',
    tax_asset: '[data-name="tax_asset"]',
    price: '[data-name="price"]',
    date_start: '[data-name="date_start"]',
    pictures: '[data-name="pictures"]',
    uploadedPictureList:'.ff-uploaded-list',
    uploadedPicture: '.ff-upload-details',
    name_full: '[data-name="name_full"]',
    phone_number: '[data-name="phone_number"]',
    submitButton: '[type="submit"]',
    successMessage: '[id="fluentform_8_success"]',
    
};